Music/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

root 'artists#index'
# root 'albums#index'

#  get 'albums/index'

resources :artists
resources :album
resources :songs

end

Music/app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artist
    has_many :songs
end

Music/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Music/app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
    has_many :songs , through: :albums
end

Music/app/models/song.rb
class Song < ApplicationRecord
belongs_to :album
end

Music/app/controllers/album_controller.rb
class AlbumController < ApplicationController
  def index
 
      @albums =  Album.all
      # render json: @albums

  end

  def show
    @album = Album.find(params[:id])
  end
end

Music/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Music/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
end

def show
  @artist = Artist.find(params[:id])
end
end

Music/app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
  end
end

Music/app/helpers/album_helper.rb
module AlbumHelper
end

Music/app/helpers/application_helper.rb
module ApplicationHelper
end

Music/app/helpers/artists_helper.rb
module ArtistsHelper
end

Music/app/helpers/songs_helper.rb
module SongsHelper
end

Music/app/views/album/index.html.erb
<div class = "albom">
    
 <% @albums.each do |album| %>

<div class="card alboms" style="width: 18rem;">
        <img src=<%=album.image %> class="card-img-top" alt="...">
        <div class="card-body">
          <p class="card-text"> <%= link_to album.name , album_path(album) %></p>
        </div>

      </div>
           <%end%>

      </div>

Music/app/views/album/show.html.erb
<div class ="Artis22" >
<h1> Artist name:  <%=  @album.name %> </h1>
 

<table class="table">

  <tbody>
    <tr>
      <th scope="row">Cover Image</th>
      <td>Year </td>
      <td>Name</td>
    </tr>
    <tr>
      <th scope="row"><img class = "imageee" src=<%=  @album.image %> alt=""></th>
      <td> <%= @album.release %> </td>
      <td><%= @album.name %></td>
    </tr>
   
  </tbody>
</table>

Music/app/views/artists/index.html.erb
 <div class="card artist" style="width: 18rem; artist">
        <ul class="list-group list-group-flush">

     <% @artists.each do |artist| %>

          <li class="list-group-item"> <%= link_to artist.name, artist_path(artist) %></li>
         
        
        <% end %>
        </ul>

      </div>

Music/app/views/artists/show.html.erb
<div class ="Artis22" >
<h1> Artis name:  <%=  @artist.name %> </h1>
 

<table class="table">

  <tbody>
    <tr>
      <th scope="row">Cover Image</th>
      <td>Year</td>
      <td>Name</td>
    </tr>
    <tr>
      <th scope="row"><img class = "imageee" src=<%=  @artist.image %> alt=""></th>
      <td></td>
      <td>Thornton</td>
    </tr>
   
  </tbody>
</table>

Music/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
  <ul class="nav navbar-dark bg-dark ">
  <li class="nav-item">
    <a class="nav-link active" href="/artists">Artist</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="album">Album</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/songs">Songs</a>
  </li>
  </div>

    <%= yield %>

<script>
<ul class="nav navbar-dark bg-dark ">
  <li class="nav-item">
    <a class="nav-link active" href="#">Artist</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Album</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Songs</a>
  </li>
</script>

  </body>
</html>

Music/app/views/songs/index.html.erb
 
</ul>
  <table class="table carrrrrr">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Player</th>
            <th scope="col">Albom cover</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <% @songs.each do|song| %>
  
            <th scope="row"><%= song.name%></th>
            <td><audio controls>
            
  <source src= <%=song.url%> type="audio/ogg"></audio></td>
            <td> <img class = "imageee" src="<%=song.image%>" alt=""></td>
            <td>non</td>
          </tr>
          
<% end %>
        
   

Music/app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>